name: Haskell CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ghc-version: '8.10.4'
      cabal-version: '3.2'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-ghc-${{ env.ghc-version }}-stack-${{ hashFiles('stack.yaml.lock') }}
          restore-keys: |
            ${{ runner.os }}-ghc-${{ env.ghc-version }}-
            ${{ runner.os }}-
      - name: Setup Haskell
        uses: actions/setup-haskell@v1
        with:
          ghc-version: ${{ env.ghc-version }}
          cabal-version: ${{ env.cabal-version }}
      - name: Run build
        run: stack build
      - name: Run test
        run: stack test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run HLint
        run: curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
